version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    command: python app.py

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app  # Ensure local changes are reflected in the container
      - /app/node_modules  # Keep node_modules on the container
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev
