services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@postgres:5432/home_improvement
    networks:
      - default
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app # Ensure local changes are reflected in the container
      - /app/node_modules # Keep node_modules on the container
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - default
    command: npm run dev

  postgres:
    # image: postgres:latest # uncomment and remove build if you want default db
    build:
      context: postgres
      dockerfile: Dockerfile
    # volumes:
    # - ./postgres/data:/var/lib/postgresql/data # delete ./postgres/data for wiping data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - default
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - backend

# volumes:
networks:
  default:
    driver: bridge
