"""Add financing_details_id to Project model

Revision ID: 05a6040262c9
Revises: 7f87251dc9c5
Create Date: 2024-05-31 22:55:58.902099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05a6040262c9'
down_revision = '7f87251dc9c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('financing_detail_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'financing_details', ['financing_detail_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('financing_detail_id')

    # ### end Alembic commands ###
