"""empty message

Revision ID: 2bccbd6ffae6
Revises: e753b74bc1ba
Create Date: 2024-06-17 22:04:03.293516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bccbd6ffae6'
down_revision = 'e753b74bc1ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_bill', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('monthly_bill')

    # ### end Alembic commands ###
