"""empty message

Revision ID: 2fc9a7ce3f34
Revises: 4266de2d7a5e
Create Date: 2024-06-04 16:28:32.465093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fc9a7ce3f34'
down_revision = '4266de2d7a5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('house_sqft', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('house_sqft')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
