"""empty message

Revision ID: 4266de2d7a5e
Revises: 05a6040262c9
Create Date: 2024-06-02 09:36:08.232653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4266de2d7a5e'
down_revision = '05a6040262c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financing_details', schema=None) as batch_op:
        batch_op.drop_constraint('financing_details_project_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financing_details', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('financing_details_project_id_fkey', 'projects', ['project_id'], ['id'])

    # ### end Alembic commands ###
