"""Removing datalayers from db

Revision ID: 648eab24d3a9
Revises: 720cba43b381
Create Date: 2024-07-22 23:26:46.722985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '648eab24d3a9'
down_revision = '720cba43b381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solar_data', schema=None) as batch_op:
        batch_op.drop_column("data_layers")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solar_data', schema=None) as batch_op:
        batch_op.add_column('data_layers')
        
    # ### end Alembic commands ###
