"""empty message

Revision ID: 720cba43b381
Revises: 2bccbd6ffae6
Create Date: 2024-06-17 22:08:34.470324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '720cba43b381'
down_revision = '2bccbd6ffae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solar_annual_income', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('solar_annual_income')

    # ### end Alembic commands ###
