"""Add data column to form_data

Revision ID: 7f87251dc9c5
Revises: a74efe493043
Create Date: 2024-05-31 19:17:11.739441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f87251dc9c5'
down_revision = 'a74efe493043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.JSON, nullable=False, server_default='{}'))
        batch_op.drop_column('field_value')
        batch_op.drop_column('field_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('field_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('field_value', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('data')

    # ### end Alembic commands ###
