"""empty message

Revision ID: 908d2e7fd670
Revises: a9193b3f2d0f
Create Date: 2024-06-08 14:54:23.964421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '908d2e7fd670'
down_revision = 'a9193b3f2d0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solar_data', schema=None) as batch_op:
        batch_op.drop_constraint('solar_data_project_id_fkey', type_='foreignkey')
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solar_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('solar_data_project_id_fkey', 'projects', ['project_id'], ['id'])

    # ### end Alembic commands ###
