"""Add new fields to existing tables and rename InstallerSteps to ProjectSteps

Revision ID: a74efe493043
Revises: fb663c4ebd30
Create Date: 2024-05-31 16:57:26.802944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a74efe493043'
down_revision = 'fb663c4ebd30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('installer_steps')
    with op.batch_alter_table('financing_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_cost', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('down_payment', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('payment_due_date', sa.Date(), nullable=True))

    with op.batch_alter_table('installers', schema=None) as batch_op:
        batch_op.drop_constraint('installers_project_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('installers_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('project_id')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('installer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('site_survey_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('inspection_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('install_start_date', sa.Date(), nullable=True))
        batch_op.alter_column('project_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'installers', ['installer_id'], ['id'])
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('project_type',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('install_start_date')
        batch_op.drop_column('inspection_date')
        batch_op.drop_column('site_survey_date')
        batch_op.drop_column('installer_id')

    with op.batch_alter_table('installers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('installers_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('installers_project_id_fkey', 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('financing_details', schema=None) as batch_op:
        batch_op.drop_column('payment_due_date')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('down_payment')
        batch_op.drop_column('total_cost')

    op.create_table('installer_steps',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('installer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('progress_step', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('step_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['installer_id'], ['installers.id'], name='installer_steps_installer_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='installer_steps_pkey')
    )
    # ### end Alembic commands ###
