"""empty message

Revision ID: a9193b3f2d0f
Revises: 2fc9a7ce3f34
Create Date: 2024-06-04 16:31:49.517374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9193b3f2d0f'
down_revision = '2fc9a7ce3f34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hvac_details', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('solar_electric_bill_kwh', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('solar_panel_amount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('solar_panel_wattage', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('solar_yearly_kwh', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('solar_battery_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('solar_microinverter', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('roof_angle', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('roof_current_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('roof_new_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('roof_current_health', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('roof_current_health')
        batch_op.drop_column('roof_new_type')
        batch_op.drop_column('roof_current_type')
        batch_op.drop_column('roof_angle')
        batch_op.drop_column('solar_microinverter')
        batch_op.drop_column('solar_battery_type')
        batch_op.drop_column('solar_yearly_kwh')
        batch_op.drop_column('solar_panel_wattage')
        batch_op.drop_column('solar_panel_amount')
        batch_op.drop_column('solar_electric_bill_kwh')
        batch_op.drop_column('hvac_details')

    # ### end Alembic commands ###
