"""empty message

Revision ID: e4615c6740c6
Revises: de9352eb5d2b
Create Date: 2024-06-17 02:01:25.565781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4615c6740c6'
down_revision = 'de9352eb5d2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roof_sqft', sa.Float(), nullable=True))
        batch_op.drop_column('house_sqft')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('house_sqft', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_column('roof_sqft')

    # ### end Alembic commands ###
