"""Added sso_token to users

Revision ID: fb663c4ebd30
Revises: 
Create Date: 2024-05-28 23:06:17.817544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb663c4ebd30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sso_token', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['sso_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('sso_token')

    # ### end Alembic commands ###
