CREATE DATABASE home_improvement;
CREATE USER db_user WITH PASSWORD 'postgres';
GRANT ALL PRIVILEGES ON DATABASE home_improvement TO db_user;

GRANT ALL PRIVILEGES ON SCHEMA public TO db_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO db_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO db_user;